name: rag-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - accelerate==1.9.0
      - acres==0.5.0
      - aiocache==0.12.3
      - aiofiles==24.1.0
      - aiohttp==3.11.11
      - aiosignal==1.4.0
      - alembic==1.14.0
      - annotated-types==0.7.0
      - anthropic==0.58.2
      - anyio==4.9.0
      - appdirs==1.4.4
      - apscheduler==3.10.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asgiref==3.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - authlib==1.6.1
      - av==15.0.0
      - azure-ai-documentintelligence==1.0.2
      - azure-core==1.35.0
      - azure-identity==1.20.0
      - azure-storage-blob==12.24.1
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - bidict==0.23.1
      - bitarray==3.5.2
      - black==25.1.0
      - blinker==1.9.0
      - boto3==1.35.53
      - botocore==1.35.99
      - brotli==1.1.0
      - cachetools==5.5.2
      - certifi==2025.7.14
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - coloredlogs==15.0.1
      - configobj==5.0.9
      - configparser==7.2.0
      - contourpy==1.3.3
      - cryptography==45.0.5
      - ctranslate2==4.6.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==4.0.0
      - defusedxml==0.7.1
      - dill==0.3.8
      - distro==1.9.0
      - dnspython==2.7.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - docutils==0.21.2
      - docx2txt==0.8
      - durationpy==0.10
      - ecdsa==0.19.1
      - einops==0.8.1
      - elastic-transport==8.17.1
      - elasticsearch==9.0.1
      - email-validator==2.2.0
      - emoji==2.14.1
      - et-xmlfile==2.0.0
      - events==0.5
      - exceptiongroup==1.3.0
      - fake-useragent==2.1.0
      - fastapi==0.115.7
      - faster-whisper==1.1.1
      - fastmcp==2.10.6
      - filelock==3.18.0
      - filetype==1.2.0
      - flask==3.1.1
      - flask-cors==6.0.1
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - fpdf2==2.8.2
      - frozenlist==1.7.0
      - fs==2.4.16
      - fsspec==2025.3.0
      - ftfy==6.2.3
      - gitpython==3.1.44
      - google-api-core==2.25.1
      - google-api-python-client==2.176.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.2
      - google-cloud-core==2.4.3
      - google-cloud-storage==2.19.0
      - greenlet==3.1.1
      - grpcio==1.67.1
      - grpcio-status==1.67.1
      - h11==0.16.0
      - h2==4.2.0
      - hpack==4.1.0
      - html5lib==1.1
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.33.4
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - kiwisolver==1.4.9
      - langchain==0.3.26
      - loguru==0.7.3
      - lxml==6.0.0
      - mako==1.3.10
      - matplotlib==3.10.5
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nltk==3.9.1
      - numpy==1.26.4
      - oauthlib==3.3.1
      - olefile==0.47
      - onnxruntime==1.20.1
      - openai==1.97.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - pandas==2.2.3
      - passlib==1.7.4
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - portalocker==2.10.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - psycopg2-binary==2.9.9
      - pyasn1==0.4.8
      - pyasn1-modules==0.4.1
      - pydantic==2.11.7
      - pydot==4.0.1
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pymongo==4.13.2
      - pymupdf==1.26.3
      - pymysql==1.1.1
      - pypdf==4.3.1
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - qdrant-client==1.14.3
      - rapidfuzz==3.13.0
      - redis==6.2.0
      - regex==2024.11.6
      - requests==2.32.4
      - rich==13.9.4
      - scikit-learn==1.7.1
      - scipy==1.16.0
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.0
      - shapely==2.1.1
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.38
      - starlette==0.45.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.2
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.53.3
      - typer==0.16.0
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - tzlocal==5.3.1
      - ujson==5.10.0
      - unstructured==0.16.17
      - urllib3==2.5.0
      - uvicorn==0.34.2
      - validators==0.35.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xlrd==2.0.1
      - xlsxwriter==3.2.5
      - xmltodict==0.14.2
      - xxhash==3.5.0
      - yarl==1.20.1
      - youtube-transcript-api==1.1.0
